# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KeyTakeaway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takeaway', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentsummary.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('summary', models.TextField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentsummary.Conference')),
                ('pillar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contentsummary.Pillar')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentsummary.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentsummary.Session')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentsummary.Speaker')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentsummary.Session'),
        ),
        migrations.AddField(
            model_name='quote',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentsummary.Speaker'),
        ),
        migrations.AddField(
            model_name='keytakeaway',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentsummary.Session'),
        ),
        migrations.AddField(
            model_name='conference',
            name='conference_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentsummary.ConferenceType'),
        ),
    ]
