# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentsummary', '0001_initial'),
    ]

    operations = [
    migrations.RenameField('Speaker', 'Company', 'company'),
    ]
