# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentsummary', '0002_auto_20171103_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
