# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentsummary', '0003_speaker_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='conferencetype',
            options={'ordering': ['conference_type']},
        ),
        migrations.AlterModelOptions(
            name='pillar',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ['speaker']},
        ),
        migrations.AddField(
            model_name='session',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
